### ISSUE TITLE
Exceptions.zip

### ISSUE THREAD

**Issue by ilobilo** [fwsGonzo/barebones#8]
How did you compile libc++abi.a and libgcc.a?

**Comment by fwsGonzo** [comment]
Hey. I forgot this. I believe that libc++abi.a was built from an old version of LLVM (probably 5.0). It just contains the stuff you need to enable RTTI and exceptions. libgcc.a you could plausibly link in without having to do anything. Many compilers have static run-time libraries part of the system package. So, try -lgcc or -lgcc_s and see what happens? There is also the --static-libgcc compiler option.

Building LLVM is no simple task, but it's complicated enough that I just can't go through it all here. I do encourage you to learn how to it yourself simply by trying. Enable the STATIC options for the things you care about, and realize that if you want to add the C++ standard library you are going to have to link in a ton of C standard library too. This is why we used musl in IncludeOS, however personally I think that EASTL is good enough, and often more performant in embedded.
